[book]
title = "KTPage"
authors = ["K. Takenaka"]
description = "Home page"
language = "ja"
multilingual = false
src = "src"

[build]
build-dir = "docs"
use-default-preprocessors = false

# [preprocessor.index]

[preprocessor.links]

[preprocessor.katex]
after = ["links"]

[output.html]
# mathjax-support = true

[output.html.fold]
enable = false
level = 0

[output.html.search]
enable = false

# [output.html.redirect]
